In [131]:
import numpy as np
import pandas as pd

# to visualize all the column, run the below code
pd.options.display.max_columns = None
# to show all the records, use the below code
pd.options.display.max_rows = None

## Fifa Worldcup - 2022 dataset.

You can find the dataset from [here](https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results).

Also you can directly use an url to read the dataset by using `pd.read_csv()` method. Check the below code cell.

In [132]:
# To get the details about the dataset, please visit
# https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv"
df = pd.read_csv(url)
df.head()

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,0,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,0,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,0,13,2,391,326,22,8,6,14,0,0

In [133]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sl. No                           128 non-null    int64
 1   Match No.                        128 non-null    int64
 2   Team                             128 non-null    str
 3   Against                          128 non-null    str
 4   Group                            128 non-null    str
 5   Goal                             128 non-null    int64
 6   Possession (%)                   128 non-null    int64
 7   Inside Penalty Area              128 non-null    int64
 8   Outside Penalty Area             128 non-null    int64
 9   Assists                          128 non-null    int64
 10  Total Attempts                   128 non-null    int64
 11  On Target                        128 non-null    int64
 12  Off Target                       128 non-null    int64
 13  Target in Penalty                128 non-null    int64
 14  Target from Outside              128 non-null    int64
 15  Left Channel                     128 non-null    int64
 16  Left Inside Channel              128 non-null    int64
 17  Central Channel                  128 non-null    int64
 18  Right Inside Channel             128 non-null    int64
 19  Right Channel                    128 non-null    int64
 20  Receptions MD                    128 non-null    int64
 21  Receptions D                     128 non-null    int64
 22  Attempted Line Breaks            128 non-null    int64
 23  Completed Line Breaks            128 non-null    int64
 24  Attempted Defensive Line Breaks  128 non-null    int64
 25  Completed Defensive Line Breaks  128 non-null    int64
 26  Yellow Cards                     128 non-null    int64
 27  Red Cards                        128 non-null    int64
 28  Fouls Against                    128 non-null    int64
 29  Offsides                         128 non-null    int64
 30  Passes                           128 non-null    int64
 31  Passes Completed                 128 non-null    int64
 32  Crosses                          128 non-null    int64
 33  Crosses Completed                128 non-null    int64
 34  Corners                          128 non-null    int64
 35  Free Kicks                       128 non-null    int64
 36  Penalties Scored                 128 non-null    int64
 37  Pts                              128 non-null    int64
dtypes: int64(35), str(3)
memory usage: 38.1 KB

In [134]:
df.head(2)

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3

### `Q-1:` Use the football dataset. Find out the total percentages that each team made on target. Display the result as a python dictionary where the keys are the team list and the values are the percentage values. Round off the percentage values up to 2 decimal places.

*Help:*
- First, find out how many total teams are participated in this worldcup. For that, you can use `unique()` method on the column "Team" or "Against".
- Loop through the teams list that you have found in previous section, and then filter the dataset according to that. After filtering the dataset, find out total attempts sum and total on target sum.
- After getting these values, find out the percentage by total on target divided by total attempts and multiply by 100. And store to a python dictionary where the key will be the team name and the values will be the percentages.
- At the end,sort the dictionary by the values (not by the keys) and print the result.


**Sample Output:**
```bash
{'Costa Rica': 54.55,
 'Cameroon': 51.85,
 'Ecuador': 48.15,
 'Argentina': 46.99,
 'Brazil': 45.56,
 'England': 45.0,
 'Portugal': 40.32,
 'Ghana': 40.0,
 'Netherlands': 39.02,
 'Korea Republic': 36.73,
 'Australia': 36.0,
 'Mexico': 34.88,
 'Croatia': 34.78,
 'Germany': 34.33,
 'France': 32.97,
 'Spain': 32.69,
 'Belgium': 32.35,
 'Serbia': 32.26,
 'Iran': 31.43,
 'Uruguay': 31.25,
 'United States': 31.11,
 'Saudi Arabia': 31.03,
 'Senegal': 30.77,
 'Denmark': 30.56,
 'Switzerland': 30.56,
 'Japan': 30.23,
 'Wales': 29.17,
 'Qatar': 28.57,
 'Morocco': 28.3,
 'Tunisia': 26.67,
 'Poland': 25.0,
 'Canada': 17.65}
```

In [135]:
# step 1 — find unique teams
teams = df['Team'].unique()
print("Total Teams:", len(teams))

# step 2 — loop through each team and calculate percentage
result = {}

for team in teams:
    # filter rows of this team
    team_df = df[df['Team'] == team]
    
    # total attempts and on target
    total_attempts  = team_df['Total Attempts'].sum()
    total_on_target = team_df['On Target'].sum()
    
    # percentage
    percentage = (total_on_target / total_attempts) * 100
    
    # store in dictionary
    result[team] = float(round(percentage, 2))

print(result)

# step 3 — sort dictionary by values (descending) and print
result = dict(sorted(result.items(), key=lambda x: x[1], reverse=True))
print(result)

Total Teams: 32
{'Qatar': 28.57, 'Ecuador': 48.15, 'England': 45.0, 'Iran': 31.43, 'Senegal': 30.77, 'Netherlands': 39.02, 'United States': 31.11, 'Wales': 29.17, 'Argentina': 46.15, 'Saudi Arabia': 31.03, 'Denmark': 30.56, 'Tunisia': 26.67, 'Mexico': 34.88, 'Poland': 25.0, 'France': 34.65, 'Australia': 36.0, 'Morocco': 28.33, 'Croatia': 33.73, 'Germany': 34.33, 'Japan': 30.23, 'Spain': 32.69, 'Costa Rica': 54.55, 'Belgium': 32.35, 'Canada': 17.65, 'Switzerland': 30.56, 'Cameroon': 51.85, 'Uruguay': 31.25, 'Korea Republic': 36.73, 'Portugal': 40.32, 'Ghana': 40.0, 'Brazil': 45.56, 'Serbia': 32.26}
{'Costa Rica': 54.55, 'Cameroon': 51.85, 'Ecuador': 48.15, 'Argentina': 46.15, 'Brazil': 45.56, 'England': 45.0, 'Portugal': 40.32, 'Ghana': 40.0, 'Netherlands': 39.02, 'Korea Republic': 36.73, 'Australia': 36.0, 'Mexico': 34.88, 'France': 34.65, 'Germany': 34.33, 'Croatia': 33.73, 'Spain': 32.69, 'Belgium': 32.35, 'Serbia': 32.26, 'Iran': 31.43, 'Uruguay': 31.25, 'United States': 31.11, 'Saudi Arabia': 31.03, 'Senegal': 30.77, 'Denmark': 30.56, 'Switzerland': 30.56, 'Japan': 30.23, 'Wales': 29.17, 'Qatar': 28.57, 'Morocco': 28.33, 'Tunisia': 26.67, 'Poland': 25.0, 'Canada': 17.65}

### `Q-2:` Find out how many times the teams are played in this Fifa Worldcup-2022. On top of this, find out the ranks of the teams.

Note: The `DataFrame.rank()` method takes an optiinal parameter named `method`. This parameter takes different values, but one of them is `average` which is by-default. So, when you do the rank, you will get some 2.5 like floating values. But if you change the value as `first`, then you will get in integers but the datatype will be float. So, try with `method="first"` parameter.

In [136]:
df.head(2)

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3

In [137]:
# Step 1 — Count how many times each team played

# Combine both Team and Against columns into a single series
all_teams = pd.concat([df["Team"], df["Against"]])

# Count the total matches played by each team
matches_played = all_teams.value_counts()

# Assign ranks based on the number of matches played
team_rank = matches_played.rank(method='first', ascending=False)

# Create a DataFrame with match counts and ranks
result = pd.DataFrame({
    "Matches Played": matches_played,
    "Rank": team_rank
})

# Display the final result
print(result)

                Matches Played  Rank
Argentina                   14   1.0
Morocco                     14   2.0
Croatia                     14   3.0
France                      13   4.0
England                     10   5.0
Netherlands                 10   6.0
Portugal                    10   7.0
Brazil                      10   8.0
Senegal                      8   9.0
United States                8  10.0
Poland                       8  11.0
Australia                    8  12.0
Japan                        8  13.0
Spain                        8  14.0
Switzerland                  8  15.0
Korea Republic               8  16.0
Qatar                        6  17.0
Ecuador                      6  18.0
Iran                         6  19.0
Wales                        6  20.0
Saudi Arabia                 6  21.0
Denmark                      6  22.0
Tunisia                      6  23.0
Mexico                       6  24.0
Germany                      6  25.0
Costa Rica                   6  26.0
Belgium                      6  27.0
Canada                       6  28.0
Cameroon                     6  29.0
Uruguay                      6  30.0
Ghana                        6  31.0
Serbia                       6  32.0
Fram                         1  33.0

### `Q-3:` Find out these below topics:
- The information about the Fifa worldcup dataset.
- The description about the Fifa worldcup dataset
- Check is there any missing values, if there is any missing values, fill that value with the average value for that particular column.
- Drop all the duplicate rows permanently.
- Drop the columns: "Sl No", "Match No.", "Red Cards" and "Pts" permanently.

In [138]:
# info
print("Info:")
print(df.info())

Info:
<class 'pandas.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sl. No                           128 non-null    int64
 1   Match No.                        128 non-null    int64
 2   Team                             128 non-null    str
 3   Against                          128 non-null    str
 4   Group                            128 non-null    str
 5   Goal                             128 non-null    int64
 6   Possession (%)                   128 non-null    int64
 7   Inside Penalty Area              128 non-null    int64
 8   Outside Penalty Area             128 non-null    int64
 9   Assists                          128 non-null    int64
 10  Total Attempts                   128 non-null    int64
 11  On Target                        128 non-null    int64
 12  Off Target                       128 non-null    int64
 13  Target in Penalty                128 non-null    int64
 14  Target from Outside              128 non-null    int64
 15  Left Channel                     128 non-null    int64
 16  Left Inside Channel              128 non-null    int64
 17  Central Channel                  128 non-null    int64
 18  Right Inside Channel             128 non-null    int64
 19  Right Channel                    128 non-null    int64
 20  Receptions MD                    128 non-null    int64
 21  Receptions D                     128 non-null    int64
 22  Attempted Line Breaks            128 non-null    int64
 23  Completed Line Breaks            128 non-null    int64
 24  Attempted Defensive Line Breaks  128 non-null    int64
 25  Completed Defensive Line Breaks  128 non-null    int64
 26  Yellow Cards                     128 non-null    int64
 27  Red Cards                        128 non-null    int64
 28  Fouls Against                    128 non-null    int64
 29  Offsides                         128 non-null    int64
 30  Passes                           128 non-null    int64
 31  Passes Completed                 128 non-null    int64
 32  Crosses                          128 non-null    int64
 33  Crosses Completed                128 non-null    int64
 34  Corners                          128 non-null    int64
 35  Free Kicks                       128 non-null    int64
 36  Penalties Scored                 128 non-null    int64
 37  Pts                              128 non-null    int64
dtypes: int64(35), str(3)
memory usage: 38.1 KB
None

In [139]:
# description
print("\nDescription:")
print(df.describe())

Description:
           Sl. No   Match No.        Goal  Possession (%)  Inside Penalty Area  Outside Penalty Area     Assists  Total Attempts   On Target  Off Target  Target in Penalty  Target from Outside  \
count  128.000000  128.000000  128.000000      128.000000           128.000000            128.000000  128.000000      128.000000  128.000000  128.000000         128.000000           128.000000
mean    64.500000   32.500000    1.343750       43.476562             1.203125              0.117188    0.914062       11.257812    4.007812    4.835938           6.914062             4.343750
std     37.094474   18.545539    1.342448       11.442403             1.324270              0.322907    1.150333        5.406683    2.588576    2.610630           3.998085             2.733397
min      1.000000    1.000000    0.000000       14.000000             0.000000              0.000000    0.000000        0.000000    0.000000    0.000000           0.000000             0.000000
25%     32.750000   16.750000    0.000000       35.000000             0.000000              0.000000    0.000000        7.750000    2.000000    3.000000           4.000000             3.000000
50%     64.500000   32.500000    1.000000       45.000000             1.000000              0.000000    1.000000       10.000000    4.000000    4.000000           6.000000             4.000000
75%     96.250000   48.250000    2.000000       51.000000             2.000000              0.000000    1.000000       14.000000    6.000000    6.000000           9.000000             5.000000
max    128.000000   64.000000    7.000000       78.000000             7.000000              1.000000    6.000000       32.000000   13.000000   17.000000          24.000000            15.000000

       Left Channel  Left Inside Channel  Central Channel  Right Inside Channel  Right Channel  Receptions MD  Receptions D  Attempted Line Breaks  Completed Line Breaks  \
count    128.000000           128.000000       128.000000            128.000000     128.000000     128.000000    128.000000             128.000000             128.000000
mean      13.562500             4.671875         4.906250              4.648438      12.234375      92.703125     12.453125             169.281250             109.476562
std        6.901729             2.886595         3.080131              2.936573       6.176517      29.440547     18.152399              34.120661              30.776298
min        2.000000             0.000000         0.000000              0.000000       1.000000      32.000000      0.000000              56.000000              19.000000
25%        8.000000             2.000000         3.000000              3.000000       8.000000      72.750000      7.000000             149.500000              87.750000
50%       12.000000             4.500000         4.000000              4.000000      11.000000      93.000000      9.000000             170.500000             106.000000
75%       18.000000             7.000000         6.250000              6.000000      16.250000     111.250000     14.000000             188.000000             129.000000
max       36.000000            13.000000        16.000000             19.000000      29.000000     186.000000    192.000000             259.000000             192.000000

       Attempted Defensive Line Breaks  Completed Defensive Line Breaks  Yellow Cards   Red Cards  Fouls Against    Offsides       Passes  Passes Completed     Crosses  Crosses Completed  \
count                       128.000000                       128.000000    128.000000  128.000000     128.000000  128.000000   128.000000        128.000000  128.000000         128.000000
mean                         14.812500                         8.265625      1.726562    0.023438      12.320312    1.976562   502.859375        430.929688   19.523438           4.898438
std                           7.230458                         5.101311      1.514834    0.151883       4.691983    1.731891   160.160487        160.893724    8.596799           3.520111
min                           1.000000                         0.000000      0.000000    0.000000       0.000000    0.000000   225.000000        156.000000    4.000000           0.000000
25%                          10.000000                         5.000000      1.000000    0.000000       9.000000    1.000000   398.250000        323.250000   13.000000           3.000000
50%                          15.000000                         8.000000      2.000000    0.000000      12.000000    2.000000   495.500000        419.000000   19.000000           4.000000
75%                          20.000000                        11.000000      2.000000    0.000000      15.000000    3.000000   589.500000        519.750000   24.000000           6.000000
max                          40.000000                        27.000000      8.000000    1.000000      30.000000   10.000000  1070.000000        994.000000   53.000000          25.000000

          Corners  Free Kicks  Penalties Scored         Pts
count  128.000000  128.000000        128.000000  128.000000
mean     4.468750   14.250000          0.335938    1.429688
std      2.774852    4.712189          0.941412    1.389973
min      0.000000    5.000000          0.000000    0.000000
25%      2.000000   11.000000          0.000000    0.000000
50%      4.000000   14.000000          0.000000    1.000000
75%      6.000000   17.000000          0.000000    3.000000
max     14.000000   30.000000          5.000000    3.000000

In [140]:
# missing values
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
Sl. No                             0
Match No.                          0
Team                               0
Against                            0
Group                              0
Goal                               0
Possession (%)                     0
Inside Penalty Area                0
Outside Penalty Area               0
Assists                            0
Total Attempts                     0
On Target                          0
Off Target                         0
Target in Penalty                  0
Target from Outside                0
Left Channel                       0
Left Inside Channel                0
Central Channel                    0
Right Inside Channel               0
Right Channel                      0
Receptions MD                      0
Receptions D                       0
Attempted Line Breaks              0
Completed Line Breaks              0
Attempted Defensive Line Breaks    0
Completed Defensive Line Breaks    0
Yellow Cards                       0
Red Cards                          0
Fouls Against                      0
Offsides                           0
Passes                             0
Passes Completed                   0
Crosses                            0
Crosses Completed                  0
Corners                            0
Free Kicks                         0
Penalties Scored                   0
Pts                                0
dtype: int64

In [141]:
df = df.fillna(df.mean(numeric_only=True))
print("\nAfter filling missing values:")
print(df.isnull().sum())

# drop duplicate rows permanently
df.drop_duplicates(inplace = True)
print("\nAfter dropping duplicates:", df.shape)

df.drop(columns=['Sl. No', 'Match No.', 'Red Cards', 'Pts'], inplace=True)

df.head()

After filling missing values:
Sl. No                             0
Match No.                          0
Team                               0
Against                            0
Group                              0
Goal                               0
Possession (%)                     0
Inside Penalty Area                0
Outside Penalty Area               0
Assists                            0
Total Attempts                     0
On Target                          0
Off Target                         0
Target in Penalty                  0
Target from Outside                0
Left Channel                       0
Left Inside Channel                0
Central Channel                    0
Right Inside Channel               0
Right Channel                      0
Receptions MD                      0
Receptions D                       0
Attempted Line Breaks              0
Completed Line Breaks              0
Attempted Defensive Line Breaks    0
Completed Defensive Line Breaks    0
Yellow Cards                       0
Red Cards                          0
Fouls Against                      0
Offsides                           0
Passes                             0
Passes Completed                   0
Crosses                            0
Crosses Completed                  0
Corners                            0
Free Kicks                         0
Penalties Scored                   0
Pts                                0
dtype: int64

After dropping duplicates: (128, 38)

,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored
0,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,15,3,453,387,10,5,1,19,0
1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,15,4,484,419,26,10,3,17,1
2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,9,2,810,733,29,9,8,16,0
3,Iran,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,14,2,232,156,11,3,0,10,1
4,Senegal,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,13,2,391,326,22,8,6,14,0

### `Q-4:` Do these below operations:
- Find out the rank based on the "Team" column and save the result by adding a new column named "Rank".
- Change the datatype of this column to integer by using `np.int16`
- Set the index of the DataFrame by using this "Rank" column permanently.
- After that, sort the dataframe based on the "Rank" index.

In [142]:
# rank based on Team column
df['Rank'] = df['Team'].rank(method='first').astype(np.int16)
print("After adding Rank column:")
print(df[['Team', 'Rank']].head())

# set Rank as index permanently
df.set_index('Rank', inplace=True)
print("\nAfter setting Rank as index:")
print(df.head())

# sort by Rank index
df.sort_index(inplace=True)
print("\nAfter sorting by Rank:")
print(df.head(10))

After adding Rank column:
      Team  Rank
0    Qatar    95
1  Ecuador    39
2  England    42
3     Iran    60
4  Senegal   101

After setting Rank as index:
         Team      Against Group  Goal  Possession (%)  Inside Penalty Area  Outside Penalty Area  Assists  Total Attempts  On Target  Off Target  Target in Penalty  Target from Outside  \
Rank
95      Qatar      Ecuador     A     0              40                    0                     0        0               5          0           5                  2                    3
39    Ecuador        Qatar     A     2              46                    2                     0        1               5          5           2                  4                    1
42    England         Iran     B     6              69                    6                     0        6              13          7           3                 10                    3
60       Iran      England     B     2              20                    2                     0        1               8          3           4                  6                    2
101   Senegal  Netherlands     A     0              39                    0                     0        0              15          4           7                  8                    7

      Left Channel  Left Inside Channel  Central Channel  Right Inside Channel  Right Channel  Receptions MD  Receptions D  Attempted Line Breaks  Completed Line Breaks  \
Rank
95              15                    0                3                     1              9             45             5                    159                    100
39               8                    7                6                     4              6             55            10                    159                    103
42              11                    5                2                     3             11             72            15                    133                     94
60               3                    0                3                     1              1             34             1                     56                     19
101             12                    4                2                     4             13            101            12                    143                     86

      Attempted Defensive Line Breaks  Completed Defensive Line Breaks  Yellow Cards  Fouls Against  Offsides  Passes  Passes Completed  Crosses  Crosses Completed  Corners  Free Kicks  \
Rank
95                                  6                                4             4             15         3     453               387       10                  5        1          19
39                                  6                                4             2             15         4     484               419       26                 10        3          17
42                                  8                                6             0              9         2     810               733       29                  9        8          16
60                                  1                                1             2             14         2     232               156       11                  3        0          10
101                                 6                                6             2             13         2     391               326       22                  8        6          14

      Penalties Scored
Rank
95                   0
39                   1
42                   0
60                   1
101                  0

After sorting by Rank:
           Team       Against Group  Goal  Possession (%)  Inside Penalty Area  Outside Penalty Area  Assists  Total Attempts  On Target  Off Target  Target in Penalty  Target from Outside  \
Rank
1     Argentina  Saudi Arabia     C     1              51                    1                     0        0              14          6           6                 10                    4
2     Argentina        Mexico     C     2              50                    1                     1        2               5          2           3                  2                    3
3     Argentina        Poland     C     2              67                    1                     1        2              25         13           8                 10                   15
4     Argentina     Australia     C     2              53                    2                     0        1              14          5           7                 11                    3
5     Argentina   Netherlands     C     2              44                    2                     0        1              15          6           8                  5                   10
6     Argentina       Croatia     C     3              34                    3                     0        1              10          7           2                  7                    3
7     Argentina        France     C     3              46                    3                     0        1              21          9           9                 13                    8
8     Australia        France     D     1              35                    1                     0        1               4          1           3                  2                    2
9     Australia       Tunisia     D     1              31                    1                     0        1               8          2           3                  5                    3
10    Australia       Denmark     D     1              24                    1                     0        1               8          4           2                  3                    5

      Left Channel  Left Inside Channel  Central Channel  Right Inside Channel  Right Channel  Receptions MD  Receptions D  Attempted Line Breaks  Completed Line Breaks  \
Rank
1               12                    4                5                     8             18             91            27                    195                    127
2               10                    6                2                     4             12             89             2                    150                    100
3               25                    8                7                    10             26            150            36                    141                    126
4               15                    6               11                     2             17            127             8                    181                    135
5                7                    7               13                     6             17            104             7                    203                    122
6                8                    9                7                     3              2            121             7                    147                     91
7               13                    6                8                     9              9            163            28                    249                    172
8               11                    2                5                     1              9             66             7                    133                     84
9               11                    3                4                     7             19            111             8                    171                     91
10               9                    2                2                     1             11             93             8                    166                     81

      Attempted Defensive Line Breaks  Completed Defensive Line Breaks  Yellow Cards  Fouls Against  Offsides  Passes  Passes Completed  Crosses  Crosses Completed  Corners  Free Kicks  \
Rank
1                                  10                                8             0              7        10     593               525       36                 15        9          21
2                                  10                                5             1             15         2     533               464       14                  2        4          23
3                                  20                               16             1             11         0     862               814       22                  5        9           5
4                                  16                                8             0              8         4     711               635        6                  1        1          15
5                                  24                                8             8             18         2     603               511       16                  4        8          30
6                                  17                                7             2             15         1     408               344        8                  2        2           6
7                                  40                               24             4             26         4     648               544       20                  4        6          22
8                                  15                                7             3             11         0     466               399        9                  2        1           5
9                                  19                               10             0             15         0     334               239       23                  4        2          19
10                                 17                                7             2             11         1     286               187       11                  2        2          13

      Penalties Scored
Rank
1                    1
2                    0
3                    0
4                    0
5                    5
6                    1
7                    5
8                    0
9                    0
10                   0

In [143]:
df.head()

,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored
Rank,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,Argentina,Saudi Arabia,C,1,51,1,0,0,14,6,6,10,4,12,4,5,8,18,91,27,195,127,10,8,0,7,10,593,525,36,15,9,21,1
2,Argentina,Mexico,C,2,50,1,1,2,5,2,3,2,3,10,6,2,4,12,89,2,150,100,10,5,1,15,2,533,464,14,2,4,23,0
3,Argentina,Poland,C,2,67,1,1,2,25,13,8,10,15,25,8,7,10,26,150,36,141,126,20,16,1,11,0,862,814,22,5,9,5,0
4,Argentina,Australia,C,2,53,2,0,1,14,5,7,11,3,15,6,11,2,17,127,8,181,135,16,8,0,8,4,711,635,6,1,1,15,0
5,Argentina,Netherlands,C,2,44,2,0,1,15,6,8,5,10,7,7,13,6,17,104,7,203,122,24,8,8,18,2,603,511,16,4,8,30,5

## Questions on Titanic dataset.

You can get the dataset from [here](https://www.kaggle.com/competitions/titanic). This is the competition page on Kaggle. To download the dataset from here, I guess you have to register for the compition. So, do so and then download the dataset.

Also, for now you can use this url to read the dataset like before:
- dataset 1: https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv
- dataset 2: https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv

### `Q-5:` Do the below tasks:
1. With dataset 1, drop those records which only have missing values of the "Age" column permanently.

2. With the dataset 2, fill the missing values with 20 to the only "Age" column permanently.

In [144]:
df1 = pd.read_csv("test - test.csv")
print(df1.shape)
print(df1.isnull().sum())

(418, 11)
PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [145]:
df1.dropna(subset=['Age'], inplace=True)
print(df1.shape)
print(df1.isnull().sum())

(332, 11)
PassengerId      0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          245
Embarked         0
dtype: int64

In [146]:
df2 = pd.read_csv("train - train.csv")
print(df2.shape)
print(df2.isnull().sum())

(891, 12)
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [147]:
# correct way — direct assignment
df2['Age'] = df2['Age'].fillna(20)

print(df2['Age'].isnull().sum())  # should be 0
print(df2['Age'].head(10))

0
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5    20.0
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

## Questions on IPL dataset

matches dataset = https://drive.google.com/file/d/1yKVUuexl6lIKuFQy7uIPgDgXhJ0L4SIg/view?usp=share_link

Code to directly use in colab
```
ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv"

```

### `Q-6:` Make a dataframe of each team in IPL with details like - Team Name, Matches Played, Win%, Home Win%, Away Win%.
Show sorted dataframe on Win%

Replace old team name as new name before performing any tasks.
```
Delhi Daredevils ->Delhi Capitals
Kings XI Punjab -> Punjab Kings
Rising Pune Supergiants -> Rising Pune Supergiant
```

Note: Team1 represents Home team. Exclude not result matches.

In [148]:
ipl_matches = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv")

print(ipl_matches.shape)
print(ipl_matches.columns.tolist())
print(ipl_matches.head(3))

(950, 20)
['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2', 'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam', 'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players', 'Team2Players', 'Umpire1', 'Umpire2']
        ID       City        Date Season  MatchNumber                        Team1                 Team2                             Venue            TossWinner TossDecision SuperOver  \
0  1312200  Ahmedabad  2022-05-29   2022        Final             Rajasthan Royals        Gujarat Titans  Narendra Modi Stadium, Ahmedabad      Rajasthan Royals          bat         N
1  1312199  Ahmedabad  2022-05-27   2022  Qualifier 2  Royal Challengers Bangalore      Rajasthan Royals  Narendra Modi Stadium, Ahmedabad      Rajasthan Royals        field         N
2  1312198    Kolkata  2022-05-25   2022   Eliminator  Royal Challengers Bangalore  Lucknow Super Giants             Eden Gardens, Kolkata  Lucknow Super Giants        field         N

                   WinningTeam    WonBy  Margin method Player_of_Match                                       Team1Players                                       Team2Players        Umpire1  \
0               Gujarat Titans  Wickets     7.0    NaN       HH Pandya  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...    CB Gaffaney
1             Rajasthan Royals  Wickets     7.0    NaN      JC Buttler  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...    CB Gaffaney
2  Royal Challengers Bangalore     Runs    14.0    NaN      RM Patidar  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...  ['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...  J Madanagopal

       Umpire2
0  Nitin Menon
1  Nitin Menon
2     MA Gough

In [ ]:
# Performing data analysis on the IPL dataset
# rename old team names
rename_map = {
    'Delhi Daredevils'       : 'Delhi Capitals',
    'Kings XI Punjab'        : 'Punjab Kings',
    'Rising Pune Supergiants': 'Rising Pune Supergiant',
}
for col in ['Team1', 'Team2', 'TossWinner', 'WinningTeam']:
    ipl_matches[col] = ipl_matches[col].replace(rename_map)

# exclude no result matches
df = ipl_matches[ipl_matches['WinningTeam'].notna()]

print(df.shape)
print(df['WinningTeam'].unique())

(946, 20)
<StringArray>
[             'Gujarat Titans',            'Rajasthan Royals', 'Royal Challengers Bangalore',                'Punjab Kings',              'Mumbai Indians',        'Lucknow Super Giants',
         'Sunrisers Hyderabad',              'Delhi Capitals',       'Kolkata Knight Riders',         'Chennai Super Kings',      'Rising Pune Supergiant',               'Gujarat Lions',
               'Pune Warriors',             'Deccan Chargers',        'Kochi Tuskers Kerala']
Length: 15, dtype: str

In [150]:
# all unique teams
teams = pd.concat([df['Team1'], df['Team2']]).unique()
print("Total Teams:", len(teams))
print(teams)

Total Teams: 15
<StringArray>
[           'Rajasthan Royals', 'Royal Challengers Bangalore',         'Sunrisers Hyderabad',              'Delhi Capitals',         'Chennai Super Kings',              'Gujarat Titans',
        'Lucknow Super Giants',       'Kolkata Knight Riders',                'Punjab Kings',              'Mumbai Indians',      'Rising Pune Supergiant',               'Gujarat Lions',
               'Pune Warriors',             'Deccan Chargers',        'Kochi Tuskers Kerala']
Length: 15, dtype: str

In [151]:
# step — calculate stats for each team
result = []

for team in teams:
    # all matches of this team
    matches = df[(df['Team1'] == team) | (df['Team2'] == team)]
    
    # home matches (Team1 = home)
    home = df[df['Team1'] == team]
    
    # away matches (Team2 = away)
    away = df[df['Team2'] == team]
    
    # wins
    total_wins = (matches['WinningTeam'] == team).sum()
    home_wins  = (home['WinningTeam'] == team).sum()
    away_wins  = (away['WinningTeam'] == team).sum()
    
    # percentages
    win_pct      = round(total_wins / len(matches) * 100, 2)
    home_win_pct = round(home_wins  / len(home)    * 100, 2) if len(home) > 0 else 0
    away_win_pct = round(away_wins  / len(away)    * 100, 2) if len(away) > 0 else 0
    
    result.append({
        'Team'         : team,
        'Matches Played': len(matches),
        'Win%'         : win_pct,
        'Home Win%'    : home_win_pct,
        'Away Win%'    : away_win_pct
    })

# convert to dataframe and sort by Win%
result_df = pd.DataFrame(result).sort_values('Win%', ascending=False)
result_df.reset_index(drop=True, inplace=True)
result_df.set_index('Team', inplace=True)
print(result_df)

                             Matches Played   Win%  Home Win%  Away Win%
Team
Gujarat Titans                           16  75.00      57.14      88.89
Lucknow Super Giants                     15  60.00      87.50      28.57
Chennai Super Kings                     208  58.17      58.56      57.73
Mumbai Indians                          231  56.71      58.04      55.46
Kolkata Knight Riders                   223  51.12      53.33      49.15
Rajasthan Royals                        190  50.53      55.06      46.53
Rising Pune Supergiant                   30  50.00      50.00      50.00
Sunrisers Hyderabad                     152  49.34      52.17      46.99
Royal Challengers Bangalore             223  48.88      49.59      48.00
Delhi Capitals                          222  46.40      46.90      45.87
Punjab Kings                            218  46.33      45.45      47.22
Gujarat Lions                            30  43.33      31.25      57.14
Kochi Tuskers Kerala                     14  42.86      42.86      42.86
Deccan Chargers                          75  38.67      33.33      44.44
Pune Warriors                            45  26.67      26.09      27.27

### `Q-7:` Venues with most "no result" matches.

In [152]:
# fix stadium name
ipl_matches['Venue'] = ipl_matches['Venue'].str.replace('M.Chinnaswamy Stadium', 
                                                          'M Chinnaswamy Stadium')

# now filter no result matches
no_result = ipl_matches[ipl_matches['WinningTeam'].isna()]
print(no_result['Venue'].value_counts())

Venue
M Chinnaswamy Stadium    3
Feroz Shah Kotla         1
Name: count, dtype: int64

}

In [153]:
ipl_matches.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

### `Q-8:` Player with most appearance in final match.

`Team1Players` and `Team2Players` have all players name. It is not a list of players name instead it is str. So handle it as string.

Hint: split and strip will help; Make a series of all players in final and do value counts

```

In [154]:
# filter final matches
finals = ipl_matches[ipl_matches['MatchNumber'] == 'Final']

print(finals.shape)
print(finals['Team1Players'].iloc[0])
print(type(finals['Team1Players'].iloc[0]))

(15, 20)
['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D Padikkal', 'SO Hetmyer', 'R Ashwin', 'R Parag', 'TA Boult', 'OC McCoy', 'M Prasidh Krishna', 'YS Chahal']
<class 'str'>

In [155]:
# combine Team1Players and Team2Players
all_players = pd.concat([finals['Team1Players'], finals['Team2Players']])

# clean and split — remove brackets and quotes, then split by comma
players_list = []
for row in all_players:
    # remove brackets and quotes
    row = row.strip("[]").replace("'", "")
    # split by comma and strip spaces
    players = [p.strip() for p in row.split(',')]
    players_list.extend(players)

# convert to series and count
players_series = pd.Series(players_list)
print(players_series.value_counts().head(10))

MS Dhoni      10
SK Raina       8
R Ashwin       7
AT Rayudu      7
RA Jadeja      7
DJ Bravo       7
RG Sharma      6
KA Pollard     6
HH Pandya      5
SL Malinga     5
Name: count, dtype: int64

In [156]:
# top player with most final appearances
top_player = players_series.value_counts().index[0]
top_count  = players_series.value_counts().iloc[0]

print(f"Player with most final appearances: {top_player} ({top_count} times)")

Player with most final appearances: MS Dhoni (10 times)

### `Q-9:` IPL Point Table

Make a function `point_table` which take `season` as parameter and show points table in non-ascendng order of points and in ascending order of team name.

For winning - 2 Ponits;

For loosing - 0 Point


For not result both team gets 1 points.

Make dataframe which will have
`TeamName` `MatchesPlayed` `MatchesWon` `NoResult` `Points`
make `TeamName` as index.

```
season parametr should be one of these->
['2022', '2021', '2020/21', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2009/10', '2009', '2007/08']
```

Output of two Top 2 in season 2022
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points

Gujarat Titans	    16	   12	       0	     24
Rajasthan Royals	17	   10	       0	     20

```

In [157]:
print(ipl_matches['Season'].unique())
print(ipl_matches['Season'].dtype)

<StringArray>
['2022', '2021', '2020/21', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2009/10', '2009', '2007/08']
Length: 15, dtype: str
str

In [158]:
def point_table(season):
    # filter by season
    season_df = ipl_matches[ipl_matches['Season'] == season]
    
    # all unique teams
    teams = pd.concat([season_df['Team1'], season_df['Team2']]).unique()
    
    result = []
    for team in teams:
        # all matches of this team
        matches = season_df[(season_df['Team1'] == team) | (season_df['Team2'] == team)]
        
        # no result matches
        no_result = matches[matches['WinningTeam'].isna()]
        
        # won matches
        won = (matches['WinningTeam'] == team).sum()
        
        # points
        points = (won * 2) + len(no_result)
        
        result.append({
            'TeamName'      : team,
            'MatchesPlayed' : len(matches),
            'MatchesWon'    : won,
            'NoResult'      : len(no_result),
            'Points'        : points
        })
    
    # convert to dataframe
    result_df = pd.DataFrame(result)
    
    # set index
    result_df.set_index('TeamName', inplace=True)
    
    # sort by Points descending, then TeamName ascending
    result_df = result_df.sort_values(['Points', 'TeamName'], 
                                       ascending=[False, True])
    return result_df

# call the function
print(point_table('2022'))

                             MatchesPlayed  MatchesWon  NoResult  Points
TeamName
Gujarat Titans                          16          12         0      24
Rajasthan Royals                        17          10         0      20
Lucknow Super Giants                    15           9         0      18
Royal Challengers Bangalore             16           9         0      18
Delhi Capitals                          14           7         0      14
Punjab Kings                            14           7         0      14
Kolkata Knight Riders                   14           6         0      12
Sunrisers Hyderabad                     14           6         0      12
Chennai Super Kings                     14           4         0       8
Mumbai Indians                          14           4         0       8

### `Q-10:` IPL Point Table cont.
Extend the above IPL Point Table with an extra column as `SeasonPosition`

Team below top 4 after sorting on `Points` and then on `TeamName` Will have same `SeasonPosition` as there rank. use rank function.


Teams in Top four will have `SeasonPosition` as:
```
    'Winner' - Team won final
    'Runner' - Team lost Final
    3 - Losing Team in Qualifier2
    4 - Losing Team in Eliminator
```

For changing value of pariticular cell use `df.at[row_index, col_label] = value`

Output of two Top 2 in season 2022. Your result should have all teams.
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points   SeasonPosition

Gujarat Titans	    16	   12	       0	     24         Winner
Rajasthan Royals	  17	   10	       0	     20         Runner

```

Note: If you try to chnage value of view of any dataframe a warnig will be shown. To avoid it, make a copy of the dataframe you want to change in by `df.copy()`

In [159]:
# check match types
print(ipl_matches['MatchNumber'].unique())

<StringArray>
[             'Final',        'Qualifier 2',         'Eliminator',        'Qualifier 1',                 '70',                 '69',                 '68',                 '67',                 '66',
                 '65',                 '64',                 '63',                 '62',                 '61',                 '60',                 '59',                 '58',                 '57',
                 '56',                 '55',                 '54',                 '53',                 '52',                 '51',                 '50',                 '49',                 '48',
                 '47',                 '46',                 '45',                 '44',                 '43',                 '42',                 '41',                 '40',                 '39',
                 '38',                 '37',                 '36',                 '35',                 '34',                 '33',                 '32',                 '31',                 '30',
                 '29',                 '28',                 '27',                 '26',                 '25',                 '24',                 '23',                 '22',                 '21',
                 '20',                 '19',                 '18',                 '17',                 '16',                 '15',                 '14',                 '13',                 '12',
                 '11',                 '10',                  '9',                  '8',                  '7',                  '6',                  '5',                  '4',                  '3',
                  '2',                  '1',          'Qualifier',  'Elimination Final',                 '72',                 '71', '3rd Place Play-Off',         'Semi Final']
Length: 80, dtype: str

In [160]:
# filter 2022 season special matches
season = '2022'
season_df = ipl_matches[ipl_matches['Season'] == season]

# final match
final = season_df[season_df['MatchNumber'] == 'Final']

# qualifier 2
qual2 = season_df[season_df['MatchNumber'] == 'Qualifier 2']

# eliminator
elim = season_df[season_df['MatchNumber'] == 'Eliminator']

print("Final:\n", final[['Team1', 'Team2', 'WinningTeam']])
print("\nQualifier 2:\n", qual2[['Team1', 'Team2', 'WinningTeam']])
print("\nEliminator:\n", elim[['Team1', 'Team2', 'WinningTeam']])

Final:
               Team1           Team2     WinningTeam
0  Rajasthan Royals  Gujarat Titans  Gujarat Titans

Qualifier 2:
                          Team1             Team2       WinningTeam
1  Royal Challengers Bangalore  Rajasthan Royals  Rajasthan Royals

Eliminator:
                          Team1                 Team2                  WinningTeam
2  Royal Challengers Bangalore  Lucknow Super Giants  Royal Challengers Bangalore

In [ ]:
def point_table(season):
    season_df = ipl_matches[ipl_matches['Season'] == season]
    
    # all unique teams
    teams = pd.concat([season_df['Team1'], season_df['Team2']]).unique()
    
    result = []
    for team in teams:
        matches   = season_df[(season_df['Team1'] == team) | (season_df['Team2'] == team)]
        no_result = matches[matches['WinningTeam'].isna()]
        won       = (matches['WinningTeam'] == team).sum()
        points    = (won * 2) + len(no_result)
        
        result.append({
            'TeamName'      : team,
            'MatchesPlayed' : len(matches),
            'MatchesWon'    : won,
            'NoResult'      : len(no_result),
            'Points'        : points
        })
    
    # Create a copy of the DataFrame to avoid warnings.
    result_df = pd.DataFrame(result).copy()
    result_df.set_index('TeamName', inplace=True)
    result_df = result_df.sort_values(['Points', 'TeamName'], ascending=[False, True])
    
    # Season position — using rank
    result_df['SeasonPosition'] = result_df['Points'].rank(method='first', ascending=False).astype(int)
    
    # special matches
    final = season_df[season_df['MatchNumber'] == 'Final'].iloc[0]
    qual2 = season_df[season_df['MatchNumber'] == 'Qualifier 2'].iloc[0]
    elim  = season_df[season_df['MatchNumber'] == 'Eliminator'].iloc[0]
    
    # # winner and runner
    winner = final['WinningTeam']
    runner = final['Team1'] if final['Team2'] == winner else final['Team2']
    
    # qualifier 2 loser → position 3
    qual2_loser = qual2['Team1'] if qual2['Team2'] == qual2['WinningTeam'] else qual2['Team2']
    
    # eliminator loser → position 4
    elim_loser = elim['Team1'] if elim['Team2'] == elim['WinningTeam'] else elim['Team2']
    
    # # set top 4 positions
    # convert SeasonPosition to object dtype first
    result_df['SeasonPosition'] = result_df['SeasonPosition'].astype(object)

    # Now you can assign string values.
    result_df.at[winner,      'SeasonPosition'] = 'Winner'
    result_df.at[runner,      'SeasonPosition'] = 'Runner'
    result_df.at[qual2_loser, 'SeasonPosition'] = 3
    result_df.at[elim_loser,  'SeasonPosition'] = 4
    
    return result_df

In [ ]:
# Display the DataFrame in a wider format
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)

# call
print(point_table('2022'))

                             MatchesPlayed  MatchesWon  NoResult  Points SeasonPosition
TeamName
Gujarat Titans                          16          12         0      24         Winner
Rajasthan Royals                        17          10         0      20         Runner
Lucknow Super Giants                    15           9         0      18              4
Royal Challengers Bangalore             16           9         0      18              3
Delhi Capitals                          14           7         0      14              5
Punjab Kings                            14           7         0      14              6
Kolkata Knight Riders                   14           6         0      12              7
Sunrisers Hyderabad                     14           6         0      12              8
Chennai Super Kings                     14           4         0       8              9
Mumbai Indians                          14           4         0       8             10